name: banq-testing
services:
  database:
    image: postgres:15.1-alpine
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "testing", "-U", "testing" ]
      interval: 1s
      start_period: 10s
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: testing
      POSTGRES_USER: testing
      POSTGRES_PASSWORD: testing
  testing:
    image: ghcr.io/thegardenboys/banq-backend-app:testing
    depends_on:
      database:
        condition: service_healthy
    environment:
      APP_NAME: "BanQ Server"
      APP_ENV: testing
      APP_KEY: base64:2bUUbbptoA/6QgCf/FihBkPS8LyE8spxS74YIEYu+UQ=
      APP_DEBUG: true
      DB_CONNECTION: pgsql
      DB_HOST: database
      DB_DATABASE: testing
      DB_USERNAME: testing
      DB_PASSWORD: testing
      BROADCAST_DRIVER: log

volumes:
  database: { }
