name: Test

on:
  pull_request:
  workflow_call:

permissions:
  contents: read
  packages: read

jobs:
  test-app:
    name: Test app
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repositories
        uses: actions/checkout@v3

      - name: Setup Docker BuildX Instance
        uses: docker/setup-buildx-action@v2

      - name: Generate cache tag for app image
        uses: docker/metadata-action@v4
        id: cache-app
        with:
          images: |
            ghcr.io/${{ github.repository }}-app
          tags: |
            type=ref,event=branch
            type=raw,enable=${{ github.event_name == 'pull_request' }},value=${{ github.event.repository.default_branch }}
          flavor: |
            latest=false
            suffix=-cache

      - name: Build Testing Image
        uses: docker/bake-action@v2.3.0
        with:
          files: |
            ./docker-bake.hcl
          targets: app-testing
          set: |
            *.cache-from=type=registry,ref=${{ steps.cache-app.outputs.tags }}

      - name: Run Testing
        run: |
          cp .env.example deploy/docker/.env
          cd deploy/docker
          echo "APP_KEY=base64:2bUUbbptoA/6QgCf/FihBkPS8LyE8spxS74YIEYu+UQ=" >> .env
          docker compose run testing
